# Generated by Django 3.1.7 on 2021-03-23 09:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210323_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchlisted_by',
            field=models.ManyToManyField(blank=True, related_name='watchlisted_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
